[versions]
android-application = "8.1.1"
kotlin-android = "1.9.0"
android-library = "8.1.1"
constraintlayout = "2.1.4"
core-ktx = "1.12.0"
material = "1.10.0"
[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
cellular-kotlin-android = { id = "org.jetbrains.kotlin.android" }
cellular-android-library = { id = "com.android.library" }
cellular-maven-publish = { id = "maven-publish" }
[libraries]
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
[bundles]